### ISSUE TITLE
Storage Options

### ISSUE THREAD

**Issue by Vec7rex** [onimitch/ffxi-ashita-minimapcontrol#2]
Hello,
I set it so that the minimap disappears as soon as I open the menu/equipment, but as soon as I open the storage options (Inventory, Wardrobe...) the minimap appears again.

**Comment by onimitch** [comment]
Can you paste here what settings you've got for this addon? `ashita/config/addons/minimapcontrol/<your character>/settings.lua`

**Comment by Vec7rex** [comment]
require('common');

local settings = T{ };
settings["show_when"] = T{ };
settings["zoom"] = T{ };
settings["opacity"] = T{ };
settings["debug_menus"] = false;
settings["show_when"]["chat_expanded"] = false;
settings["show_when"]["command_menu_open"] = true;
settings["show_when"]["main_menu_open"] = false;
settings["show_when"]["any_menu_open"] = true;
settings["show_when"]["moving"] = true;
settings["show_when"]["during_events"] = false;
settings["show_when"]["auction_open"] = false;
settings["show_when"]["map_open"] = false;
settings["show_when"]["in_combat"] = true;
settings["show_when"]["window_open"] = false;

**Comment by onimitch** [comment]
Thanks I'll give it a test with your settings and see if I can find what's wrong

**Comment by onimitch** [comment]
Hey I've been trying to test this but haven't been able to find any issue using the same settings as you.
Would you mind showing a screenshot or even video that show the problem? My guess is I must be misunderstanding what menu the minimap is reappearing on.

**Comment by Vec7rex** [comment]
![1](https://github.com/onimitch/ffxi-ashita-minimapcontrol/assets/57547484/4164add9-09ca-4a83-836a-cf3da108cb1c)

**Comment by onimitch** [comment]
Thanks. I don't think I recognise those menus. How do you get to them?

**Comment by Vec7rex** [comment]
![2](https://github.com/onimitch/ffxi-ashita-minimapcontrol/assets/57547484/db28328a-6720-4bc9-bd10-e8bbd531df33)

The first picture shows the storage options (equipment > storage options)

The second picture shows the window through which you can tell other players and invite them to the group.

**Comment by onimitch** [comment]
Thanks!

**Comment by onimitch** [comment]
OK I think I got the ones you reported plus spotted a few others. Give [1.2.1](https://github.com/onimitch/ffxi-ashita-minimapcontrol/releases/tag/1.2.1) a go, hopefully all fixed!

**Comment by Vec7rex** [comment]
I tested it. Looks good so far. Many thanks for your effort.
